[tools]
"tuist" = "4.5.1"
"swiftlint" = "0.54.0"
"swiftformat" = "0.52.10"
"swift" = "5.9.2"
"pnpm" = "8.15.4"
"node" = "20.11.1"
"podman" = "4.9.3"

[plugins]
tuist = "https://github.com/asdf-community/asdf-tuist"
swift = "https://github.com/fcrespo82/asdf-swift"
podman = "https://github.com/tvon/asdf-podman.git"