[tools]
"tuist" = "4.26.0"
"swiftlint" = "0.54.0"
"swiftformat" = "0.52.10"
"pnpm" = "9.7.1"
"node" = "20.16.0"
"podman" = "4.9.3"
"git-cliff" = "2.4.0"

[plugins]
tuist = "https://github.com/asdf-community/asdf-tuist"
swift = "https://github.com/fcrespo82/asdf-swift"
podman = "https://github.com/tvon/asdf-podman.git"